name: benchmark-6

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [
          ubicloud-standard-4-ubuntu-2204,
          ubicloud-premium-4-ubuntu-2204,
          ubicloud-standard-4-ubuntu-2404,
          ubicloud-premium-4-ubuntu-2404,
        ]
    name: ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true

    steps:
    - name: Install benchmark tools
      run: |
        sudo apt-get update
        sudo apt-get install -y sysbench fio p7zip-full postgresql-client
        mkdir -p /tmp/fio
    - name: "I/O: fio random read 4K (iodepth=256)"
      run: |
        fio --name=rand-read-4k-deep --ioengine=libaio --direct=1 --bs=4k --iodepth=256 \
          --size=1G --numjobs=1 --rw=randread --group_reporting --runtime=30 --time_based \
          --directory=/tmp/fio
        sudo rm -rf /tmp/fio && mkdir -p /tmp/fio
    - name: "I/O: fio random write 4K (iodepth=256)"
      run: |
        fio --name=rand-write-4k-deep --ioengine=libaio --direct=1 --bs=4k --iodepth=256 \
          --size=1G --numjobs=1 --rw=randwrite --group_reporting --runtime=30 --time_based \
          --directory=/tmp/fio
        sudo rm -rf /tmp/fio && mkdir -p /tmp/fio
